export const GOVS = [
  { code: "01", name: "القاهرة" },
  { code: "02", name: "الجيزة" },
  { code: "03", name: "الإسكندرية" },
  { code: "04", name: "الدقهلية" },
  { code: "05", name: "البحر الأحمر" },
  { code: "06", name: "البحيرة" },
  { code: "07", name: "الفيوم" },
  { code: "08", name: "الغربية" },
  { code: "09", name: "الإسماعيلية" },
  { code: "10", name: "المنوفية" },
  { code: "11", name: "المنيا" },
  { code: "12", name: "القليوبية" },
  { code: "13", name: "الوادي الجديد" },
  { code: "14", name: "السويس" },
  { code: "15", name: "أسوان" },
  { code: "16", name: "أسيوط" },
  { code: "17", name: "بني سويف" },
  { code: "18", name: "بورسعيد" },
  { code: "19", name: "دمياط" },
  { code: "20", name: "الشرقية" },
  { code: "21", name: "جنوب سيناء" },
  { code: "22", name: "كفر الشيخ" },
  { code: "23", name: "مطروح" },
  { code: "24", name: "الأقصر" },
  { code: "25", name: "قنا" },
  { code: "26", name: "شمال سيناء" },
  { code: "27", name: "سوهاج" },
]